package me.jissee.jarsauth.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import me.jissee.jarsauth.data.model.ServerLicenseInstance;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.function.Consumer;

public class LicenseInstanceWindow extends AbstractModWindow {
    private String title;
    private JPanel panel1;
    private JButton cancelButton;
    private JButton confirmButton;
    private ServerLicenseInstance oldInstance;
    private Consumer<ServerLicenseInstance> onConfirm;

    public LicenseInstanceWindow(String title, ServerLicenseInstance oldInstance, Consumer<ServerLicenseInstance> onConfirm) {
        frame.setSize(500, 320);
        this.title = title;
        this.oldInstance = oldInstance;
        this.onConfirm = onConfirm;
        frame.setTitle(getTitle());
        cancelButton.addActionListener(this::onCancel);
        confirmButton.addActionListener(this::onConfirm);
    }

    private void onCancel(ActionEvent e) {
        dispose();
    }

    private void onConfirm(ActionEvent e) {
        this.onConfirm.accept(oldInstance);
    }

    @Override
    protected void onShow() {

    }

    @Override
    public String getTitle() {
        if (title == null) return null;
        return title;
    }

    @Override
    public JPanel getPanel() {
        return panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        cancelButton = new JButton();
        cancelButton.setText("Button");
        panel1.add(cancelButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        confirmButton = new JButton();
        confirmButton.setText("Button");
        panel1.add(confirmButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
