package me.jissee.jarsauth.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import me.jissee.jarsauth.data.model.LicenseType;
import me.jissee.jarsauth.data.model.ServerLicense;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.lang.reflect.Method;
import java.util.ResourceBundle;
import java.util.function.Consumer;

public class LicenseEditorWindow extends AbstractModWindow {
    private final String title;
    private final ServerLicense oldLicense;
    private final Consumer<ServerLicense> onConfirm;

    private JPanel panel1;
    private JTextField playerNameText;
    private JTextField validFromText;
    private JTextField validUntilText;
    private JComboBox<String> typeComboBox;
    private JTextField allowanceText;
    private JTextField periodText;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button4;

    private class KeyAdapter extends java.awt.event.KeyAdapter {
        @Override
        public void keyReleased(KeyEvent e) {
            if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                onConfirm(null);
            } else if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                dispose();
            }
        }
    }

    public LicenseEditorWindow(String title, ServerLicense oldLicense, Consumer<ServerLicense> onConfirm) {
        frame.setSize(500, 250);
        this.title = title;
        this.oldLicense = oldLicense;
        this.onConfirm = onConfirm;
        frame.setTitle(getTitle());
        button1.addActionListener(this::onCancel);
        button2.addActionListener(this::onConfirm);

        for (LicenseType type : LicenseType.values()) {
            typeComboBox.addItem(Locales.getString(type.getNameKey()));
        }


        playerNameText.setText(oldLicense.userName());
        validFromText.setText(ServerLicense.formatDate(oldLicense.validFrom()));
        validUntilText.setText(ServerLicense.formatDate(oldLicense.validUntil()));
        typeComboBox.setSelectedIndex(oldLicense.type().ordinal());
        allowanceText.setText(oldLicense.allowance().toString());
        periodText.setText(ServerLicense.formatPeriodTime(oldLicense.period().get()));

        playerNameText.addKeyListener(new KeyAdapter());
        validFromText.addKeyListener(new KeyAdapter());
        validUntilText.addKeyListener(new KeyAdapter());
        typeComboBox.addKeyListener(new KeyAdapter());
        allowanceText.addKeyListener(new KeyAdapter());
        periodText.addKeyListener(new KeyAdapter());
        button3.addActionListener(this::today);
    }

    private void today(ActionEvent e) {
        validFromText.setText(ServerLicense.formatDate(System.currentTimeMillis() / 1000));
    }

    private void onCancel(ActionEvent e) {
        dispose();
    }

    private void onConfirm(ActionEvent e) {
        try {
            ServerLicense newLicense = new ServerLicense(
                    oldLicense.uuid(),
                    playerNameText.getText(),
                    ServerLicense.fromFormatDate(validFromText.getText()),
                    ServerLicense.fromFormatDate(validUntilText.getText()),
                    LicenseType.values()[typeComboBox.getSelectedIndex()],
                    Long.parseLong(allowanceText.getText()),
                    ServerLicense.fromFormatPeriodTime(periodText.getText())
            );
            onConfirm.accept(newLicense);
            dispose();
        } catch (Exception ex) {
            showError(ex.toString(), "");
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(7, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("ui", "label.server.license.player"));
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        playerNameText = new JTextField();
        panel1.add(playerNameText, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        this.$$$loadLabelText$$$(label2, this.$$$getMessageFromBundle$$$("ui", "label.server.license.valid.until"));
        panel1.add(label2, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        validFromText = new JTextField();
        validFromText.setToolTipText(this.$$$getMessageFromBundle$$$("ui", "label.server.license.valid.tip"));
        panel1.add(validFromText, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        validUntilText = new JTextField();
        validUntilText.setToolTipText(this.$$$getMessageFromBundle$$$("ui", "label.server.license.valid.tip"));
        panel1.add(validUntilText, new GridConstraints(5, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        this.$$$loadLabelText$$$(label3, this.$$$getMessageFromBundle$$$("ui", "label.server.license.type"));
        panel1.add(label3, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        typeComboBox = new JComboBox();
        panel1.add(typeComboBox, new GridConstraints(1, 2, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        this.$$$loadLabelText$$$(label4, this.$$$getMessageFromBundle$$$("ui", "label.server.license.allowance"));
        panel1.add(label4, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        allowanceText = new JTextField();
        allowanceText.setToolTipText(this.$$$getMessageFromBundle$$$("ui", "label.server.license.allowance.tip"));
        panel1.add(allowanceText, new GridConstraints(3, 2, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        periodText = new JTextField();
        periodText.setToolTipText(this.$$$getMessageFromBundle$$$("ui", "label.server.license.period.tip"));
        panel1.add(periodText, new GridConstraints(5, 2, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label5 = new JLabel();
        this.$$$loadLabelText$$$(label5, this.$$$getMessageFromBundle$$$("ui", "label.server.license.period"));
        panel1.add(label5, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button1 = new JButton();
        this.$$$loadButtonText$$$(button1, this.$$$getMessageFromBundle$$$("ui", "info.cancel"));
        panel1.add(button1, new GridConstraints(6, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button2 = new JButton();
        this.$$$loadButtonText$$$(button2, this.$$$getMessageFromBundle$$$("ui", "info.confirm"));
        panel1.add(button2, new GridConstraints(6, 2, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        this.$$$loadLabelText$$$(label6, this.$$$getMessageFromBundle$$$("ui", "label.server.license.valid.from"));
        panel1.add(label6, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button3 = new JButton();
        button3.setOpaque(false);
        this.$$$loadButtonText$$$(button3, this.$$$getMessageFromBundle$$$("ui", "label.server.license.now"));
        panel1.add(button3, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button4 = new JButton();
        button4.setBorderPainted(false);
        button4.setContentAreaFilled(false);
        button4.setDefaultCapable(false);
        button4.setEnabled(false);
        button4.setOpaque(false);
        button4.setText("");
        button4.setVisible(true);
        panel1.add(button4, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    private static Method $$$cachedGetBundleMethod$$$ = null;

    private String $$$getMessageFromBundle$$$(String path, String key) {
        ResourceBundle bundle;
        try {
            Class<?> thisClass = this.getClass();
            if ($$$cachedGetBundleMethod$$$ == null) {
                Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
                $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
            }
            bundle = (ResourceBundle) $$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
        } catch (Exception e) {
            bundle = ResourceBundle.getBundle(path);
        }
        return bundle.getString(key);
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadLabelText$$$(JLabel component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) break;
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setDisplayedMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadButtonText$$$(AbstractButton component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) break;
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    @Override
    protected void onShow() {

    }

    @Override
    public String getTitle() {
        if (title == null) return null;
        return title;
    }

    @Override
    public JPanel getPanel() {
        return panel1;
    }
}
